esphome:
  name: modbus-stromzaehler
  friendly_name: Modbus Stromzaehler

esp32:
  board: esp32dev
  framework:
    type: arduino

uart:
  id: mod_uart
  tx_pin: GPIO3
  rx_pin: GPIO1
  baud_rate: 9600

modbus:
  id: modbus1
  uart_id: mod_uart

modbus_controller:
- id: modbus_stromzaehler
  address: 1
  modbus_id: modbus1
  update_interval: 5s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "your_personal_key"

ota:
  - platform: esphome
    password: "your_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Modbus-Stromzaehler"
    password: "your_password"

captive_portal:
    
sensor:

  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 1"
    register_type: holding
    address: 0x00
    value_type: U_DWORD
    unit_of_measurement: V
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 2"
    register_type: holding
    address: 0x02
    value_type: U_DWORD
    unit_of_measurement: V
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 3"
    register_type: holding
    address: 0x04
    value_type: U_DWORD
    unit_of_measurement: V
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 1 Amps"
    register_type: holding
    address: 0x06
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 2 Amps"
    register_type: holding
    address: 0x08
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 3 Amps"
    register_type: holding
    address: 0x0A
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 1 Watt"
    register_type: holding
    address: 0x0C
    value_type: S_DWORD
    unit_of_measurement: Wh
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 2 Watt"
    register_type: holding
    address: 0x0E
    value_type: S_DWORD
    unit_of_measurement: Wh
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 3 Watt"
    register_type: holding
    address: 0x10
    value_type: S_DWORD
    unit_of_measurement: Wh
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 1 Reactive Power"
    register_type: holding
    address: 0x12
    value_type: S_DWORD
    unit_of_measurement: Reactive
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 2 Reactive Power"
    register_type: holding
    address: 0x14
    value_type: S_DWORD
    unit_of_measurement: Reactive
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 3 Reactive Power"
    register_type: holding
    address: 0x16
    value_type: S_DWORD
    unit_of_measurement: Reactive
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 1 Apparent Power"
    register_type: holding
    address: 0x18
    value_type: U_DWORD
    unit_of_measurement: kVA
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 2 Apparent Power"
    register_type: holding
    address: 0x1A
    value_type: U_DWORD
    unit_of_measurement: kVA
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 3 Apparent Power"
    register_type: holding
    address: 0x1C
    value_type: U_DWORD
    unit_of_measurement: kVA
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 1 Power Factor"
    register_type: holding
    address: 0x1E
    value_type: S_WORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 2 Power Factor"
    register_type: holding
    address: 0x1F
    value_type: S_WORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 3 Power Factor"
    register_type: holding
    address: 0x20
    value_type: S_WORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 1 Phase Angle"
    register_type: holding
    address: 0x21
    value_type: S_WORD
    unit_of_measurement: °
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 2 Phase Angle"
    register_type: holding
    address: 0x22
    value_type: S_WORD
    unit_of_measurement: °
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 3 Phase Angle"
    register_type: holding
    address: 0x23
    value_type: S_WORD
    unit_of_measurement: °
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Line 1 to Line 2 Volts"
    register_type: holding
    address: 0x24
    value_type: U_DWORD
    unit_of_measurement: V
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Line 2 to Line 3 Volts"
    register_type: holding
    address: 0x26
    value_type: U_DWORD
    unit_of_measurement: V
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Line 3 to Line 1 Volts"
    register_type: holding
    address: 0x28
    value_type: U_DWORD
    unit_of_measurement: V
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Frequenz der Versorgungsspannungen"
    register_type: holding
    address: 0x2A
    value_type: S_WORD
    unit_of_measurement: Hz
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamte Systemwirkleistung"
    register_type: holding
    address: 0x2C
    value_type: S_DWORD
    unit_of_measurement: Wh
    device_class: energy
    state_class: total
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamtsystemblindleistung"
    register_type: holding
    address: 0x2E
    value_type: S_DWORD
    unit_of_measurement: kvar
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamtsystemscheinleistung"
    register_type: holding
    address: 0x30
    value_type: S_DWORD
    unit_of_measurement: kVA
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamtleistungsfaktor"
    register_type: holding
    address: 0x32
    value_type: S_WORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamtphasenwinkel"
    register_type: holding
    address: 0x33
    value_type: S_WORD
    unit_of_measurement: °
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Summe der Leitungsströme"
    register_type: holding
    address: 0x34
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Average Line to Neutral Volts"
    register_type: holding
    address: 0x36
    value_type: U_DWORD
    unit_of_measurement: V
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Average Line to Line Volts"
    register_type: holding
    address: 0x38
    value_type: U_DWORD
    unit_of_measurement: V
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Durchschnittlicher Leitungsstrom"
    register_type: holding
    address: 0x3A
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Neutraler Strom"
    register_type: holding
    address: 0x3C
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamtwirkleistungsbedarf"
    register_type: holding
    address: 0x66
    value_type: S_DWORD
    unit_of_measurement: Wh
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamter Blindleistungsbedarf"
    register_type: holding
    address: 0x68
    value_type: S_DWORD
    unit_of_measurement: kvar
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamtscheinleistungsbedarf"
    register_type: holding
    address: 0x6A
    value_type: S_DWORD
    unit_of_measurement: kVA
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 1 Aktuelle Nachfrage"
    register_type: holding
    address: 0x6C
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 2 Aktuelle Nachfrage"
    register_type: holding
    address: 0x6E
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Phase 3 Aktuelle Nachfrage"
    register_type: holding
    address: 0x70
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Maximaler Gesamtwirkleistungsbedarf"
    register_type: holding
    address: 0x7C
    value_type: S_DWORD
    unit_of_measurement: Wh
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Maximaler Gesamtblindleistungsbedarf"
    register_type: holding
    address: 0x7E
    value_type: S_DWORD
    unit_of_measurement: kvar
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Maximaler Gesamtscheinleistungsbedarf"
    register_type: holding
    address: 0x80
    value_type: U_DWORD
    unit_of_measurement: kVA
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Maximaler aktueller Bedarf der Phase 1"
    register_type: holding
    address: 0x82
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Maximaler aktueller Bedarf der Phase 2"
    register_type: holding
    address: 0x84
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Maximaler aktueller Bedarf der Phase 3"
    register_type: holding
    address: 0x86
    value_type: U_DWORD
    unit_of_measurement: A
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamtimport Wirkenergie"
    register_type: holding
    address: 0x4000
    value_type: U_DWORD
    unit_of_measurement: kWh
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamte Export-Wirkenergie"
    register_type: holding
    address: 0x4002
    value_type: U_DWORD
    unit_of_measurement: kWh
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamte aktive Energie"
    register_type: holding
    address: 0x4004
    value_type: U_DWORD
    unit_of_measurement: kWh
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamtimport-Blindenergie"
    register_type: holding
    address: 0x4008
    value_type: U_DWORD
    unit_of_measurement: kvar
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamtexport-Blindenergie"
    register_type: holding
    address: 0x400A
    value_type: U_DWORD
    unit_of_measurement: kvarh
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_stromzaehler
    name: "Gesamtreaktive Energie"
    register_type: holding
    address: 0x400C
    value_type: U_DWORD
    unit_of_measurement: kvarh
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  
